### ISSUE TITLE
My Config is right?

### ISSUE THREAD

**Issue by mberbero** [caddyserver/certmagic#178] opened 2022-03-22 21:25 UTC
## What is your question?
Hello everyone
This is how I set my config. But I keep getting rate limit errors.
Do you have any suggestions?

<img width="498" alt="Ekran Resmi 2022-03-22 23 07 57" src="https://user-images.githubusercontent.com/40326463/159578363-7fd89dc5-e03d-46d7-8fb5-7871b88d0e9a.png">

**Comment by mholt** [comment] 2022-03-22 21:34
Rate limits can be caused by a lot of things, and there are a lot of rate limits out there. We'll need your full logs to be able to help. Until then, the issue is unactionable so I will close it for now. (We can reopen it if it turns out to be a bug in CertMagic...)

**Closed by mholt** 2022-03-22 21:34 UTC
Labels: question

**Comment by mberbero** [comment] 2022-03-22 21:45
First, I get this error. After 2-3 iterations I get a rate limit error.

<img width="992" alt="Ekran Resmi 2022-03-23 00 43 06" src="https://user-images.githubusercontent.com/40326463/159581318-3b94fc66-b46f-43dd-811b-b8239bb91512.png">

**Comment by mberbero** [comment] 2022-03-22 21:49
Thank you for your help.
