### ISSUE TITLE
Empty lockfile, likely previous process crashed or storage medium failure; treating as stale

### ISSUE THREAD

**Issue by cattyhouse** [caddyserver/certmagic#232] opened 2023-05-17 04:47 UTC
since https://github.com/caddyserver/certmagic/commit/79babffe28c5e593b19b5268bf26447f1f5f0b26 , caddy produces lots of logs (32285 lines so far and keep increasing) like: https://github.com/imgk/caddy-trojan/issues/55#issue-1698507292

in above case the plugin `caddy-trojan` **does not create** `.lock` file at all.

**Suggestion**:

maybe [certmagic](https://github.com/caddyserver/certmagic) checks if `.lock` file exists before checking `io.EOF`?

**Comment by mholt** [comment] 2023-05-17 04:53
Never heard of something like this...

Are you _sure_ the .lock files don't ever exist? Because those files tend to get cleaned up pretty quick, or at least they should.

> maybe [certmagic](https://github.com/caddyserver/certmagic) checks if .lock file exists before checking io.EOF?

It is doing that already; just a few lines earlier:

https://github.com/caddyserver/certmagic/commit/79babffe28c5e593b19b5268bf26447f1f5f0b26#diff-bb094528ba8793b4ce43d063c43a23b31ca8aefbc412cbbe8dc2188b21c36022R171-R175

If the file does not exist, `os.Open()` would return an error and it wouldn't even try reading the file. So the OS is telling CertMagic that the file does in fact exist...

I'd like more details on what's actually on the disk, the contents of the files, and preferably how to reproduce this.

**Comment by mholt** [comment] 2023-05-17 05:16
I think in order to give you any answers and, if necessary, produce a patch, I'll need to be able to reproduce the behavior in the most minimal way possible.

The full and unredacted logs could be a good start, that should at least give some insight into what's going on. Make sure to enable debug-level logging (will be very noisy) and don't redact any information, as that defeats the purpose and I can't help you then. Feel free to attach the logs to a reply here.

**Comment by francislavoie** [comment] 2023-05-17 06:04
Lock files created by the filesystem storage driver https://github.com/caddyserver/certmagic/blob/8728b186fa6874e93bbc051dc73d1596dd63d390/filestorage.go#L350 contain JSON which encodes the created and updated times of the files. This is done because not all filesystems support keeping track of both those timestamps, so storing it in the file is a more reliable way to ensure we can track how long a lock has been open.

**Comment by mholt** [comment] 2023-05-17 18:48
Yeah the lockfiles don't often stay around for long.

I wonder if the file is removed after opening the file but before reading its contents. That would return an empty file maybe? Is that something you could test on your system? Create a file with some contents, then close it. Then open it, delete it, then read from it.

**Comment by mholt** [comment] 2023-05-18 00:40
No, you'll have to open the file for reading, then delete it, then read from it. Running `cat` twice will open, read, then close the file twice.

**Comment by mholt** [comment] 2023-05-18 01:57
Hmm, yeah, I don't know how you'd do it with just a shell. There might be something fancy you can do with bash but I don't know it.

Here's a simple Go program you can use to test this though:

```go
package main

import (
	"fmt"
	"io"
	"log"
	"os"
)

func main() {
	const filename = "foo.txt"

	f, err := os.Open(filename)
	if err != nil {
		log.Fatal(err)
	}

	if err = os.Remove(filename); err != nil {
		log.Fatal(err)
	}

	contents, err := io.ReadAll(f)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(string(contents))

	if err := f.Close(); err != nil {
		log.Fatal(err)
	}
}

```

First create a file called "foo.txt" (if you use a different filename, just update the program as well) with something, like: `echo "Hello world" > foo.txt`

Then run that program: `go run main.go`

See what happens?

**Comment by mholt** [comment] 2023-05-18 02:50
Ok, so that shows that when a file is deleted while opened it can still read the contents, i.e. it's not empty.

There must be some other explanation.

**Comment by mholt** [comment] 2023-05-19 19:52
Seems likely.

I'm not sure how to replace the contents of a file atomically. I thought opening a file for writing would cause other readers to block while the writer was open, but I guess not...?

**Closed** 2023-06-15 21:32 UTC
Labels: bug, help wanted

**Comment by mholt** [comment] 2023-06-15 21:36
@cattyhouse Would you mind trying with https://github.com/caddyserver/certmagic/commit/321ed6491253a852d4ccd5f6e827d7bf54bd6c3e? I'm guessing that if it's simply reading the lock file while it's still being truncated/written (not sure why that's allowed by the FS, but whatever) and thus seeing a size of 0, retrying after a brief delay should resolve the problem because by that time, the file should be fully written. If it truly is stale/abandoned, we still detect that, but it's after ~200ms instead of right away.

**Comment by mholt** [comment] 2023-06-16 05:25
@cattyhouse Ahh, dangit.

Thank you for testing, and figuring that out; this is super helpful.

So that means the file is _still_ empty (but still exists) after 200ms...? Seems extremely unlikely. Either the storage medium is very slow, or something is lying.

I mean, would we want to wait even longer? Right now we're waiting 100ms and trying up to 2 times (so 200ms). Should we be trying up to 5 times (500ms)? 10 (1s)? That seems ludicrous though. We're even closing and re-opening the file, so if the file is deleted in the meantime it shouldn't re-open successfully. That seems like a broken file system, but I can't believe ext4 would be broken like that. Is something else happening?

**Comment by mholt** [comment] 2023-06-16 05:56
(THANK YOU, by the way, for going to the effort to help try my ideas. I hope we can figure this out soon. But I'll be honest I'm running out of ideas.)

**Comment by mholt** [comment] 2023-06-16 15:56
@cattyhouse Wow, that's really interesting. I am glad we seemed to have made progress here! Thank you for troubleshooting/debugging so thoroughly.

I'm going to change the delay interval to 250ms and set the retry count to 6.

Question: Any idea why your storage backend is so slow? Are you using an SSD or an HDD? It's taking about a second to create and write a file. That's 10x longer than I would have guessed.

It does seem you are using the locks in a very busy part of the code (for every request, I think?) and the locks are very very short-lived. So there's lots of writes to disk. I could see why that's potentially slowing things down. Are you actually needing this to coordinate multiple instances in a cluster? Or is this all for a single machine? If it's just the same instance of Caddy then why not use a regular sync.Mutex...

Anyway just wanted to get some more info so I can be confident with the patch. :) Thanks

> (i am not sure if it is possible to patch a tag though)

Unfortunately tags are immutable (with respect to Go modules). This means we can't change a tag. I'll get it into the next Caddy release though: 2.7 beta 2.
