### ISSUE TITLE
Issue with resolvers

### ISSUE THREAD

**Issue by MisterDuval** [caddyserver/certmagic#219] opened 2023-03-15 15:38 UTC
Hi,
I'm having issue with resolvers, my caddyFile looks like:

[...]
tls {
   dns cloudflare MY_API_KEY
   resolvers 1.1.1.1
}
But I'm getting this error because IT blocks DNS requests except from 1.1.1.1.
"error": "[URL] solving challenges: waiting for solver certmagic.solverWrapper to be ready: checking DNS propagation of "_acme-challenge.URL": dial tcp 108.162.195.175:53: i/o timeout

This IP is related to Cloudflare NS

**Comment by mholt** [comment] 2023-03-15 15:56
Did you verify that the config you think you're running is actually the config that's running?

In isolation, the config you gave works. What is your full config that we can reproduce the issue? (Including domain names)

**Comment by MisterDuval** [comment] 2023-03-15 16:06
Yes, my config file is valid and tested, maybe that "resolvers" is just ignored? 
As soon as I allowed that other DNS IP (108.162.195.175) in firewall, it has worked.  You can try with a `ca https://acme-staging-v02.api.letsencrypt.org/directory` and a firewall blocking all DNS requests except 1.1.1.1 (port TCP 53)

Caddy v2.6.4 (on Windows), compiled with xcaddy and caddy-exec + caddy-dns-cloudflare

caddyFile:
```
{
    email MY_EMAIL
}

https://mycustomdomain.ltd
{
    tls {
   	    dns cloudflare MYAPIKEY
	    resolvers 1.1.1.1
	}

    root htdocs

    encode gzip
    file_server
    php_fastcgi 127.0.0.1:9123
    log {
       output file logs/caddy-error.log
       level ERROR
    }
}
```

**Comment by mholt** [comment] 2023-03-16 04:52
Thanks for the follow-up. It seems unlikely that they're being ignored, however, if you have a moment to try putting a `fmt.Println()` line just before this line:

https://github.com/caddyserver/certmagic/blob/3514797a52dd6e6ac316eeb791545885ffbc33b0/solvers.go#L375

And maybe a few more in the call stack down the `checkDNSPropagation()` function would likely prove which resolvers are being used. If it's not 1.1.1.1 then it should be easier to figure out why.

**Comment by mholt** [comment] 2023-06-15 21:38
@MisterDuval Any interest in digging into this?

**Comment by MisterDuval** [comment] 2023-06-16 08:44
Sorry I had no time for this for now.

**Comment by mholt** [comment] 2023-06-16 16:15
No worries. I'll probably close it for now, since I think we'll need your help to troubleshoot this. We can reopen when ready :+1:

**Comment by pgeh** [comment] 2024-03-05 13:38
I seem to have run into the same problem with caddy and a split DNS setup. As far es I can tell the problem is that the checkDNSPropagation function doesnt' use the given resolvers to get the IPs for den authoritative name servers of the domain. In my case this results in a request to the name servers internal IP and zone, where there are no TXT records, and in @MisterDuval a request to the Cloudflare DNS Server.

The problematic code is the call to checkAuthoritativeNss(...) at [](https://github.com/caddyserver/certmagic/blob/8613f4a4444987b6226a2bedb980284d11dc1f44/dnsutil.go#L234) which doesn't use the given resolvers to resolve the authoritative name servers IPs.

I tried a quick and dirty fix by resolving and returning the name server names via the resolvers in [lookupNameservers](https://github.com/caddyserver/certmagic/blob/8613f4a4444987b6226a2bedb980284d11dc1f44/dnsutil.go#L229C27-L229C44) and returning the IPs instead of the fqdns. With that it worked and caddy could finish the cert creation, but I don't think that would be a valid solution.

@mholt Does that explanation make sense to you? Imho this is a bug as the explicitly given resolvers are not used throughout the whole checkDNSPropagation(...) process. A solution would be most welcome as that prevents me to use caddy in my environment.

**Comment by mholt** [comment] 2024-03-05 16:12
@pgeh Actually I'd be interested in seeing the patch as a PR so I can review it, if you'd be ok with that! Why wouldn't it be a valid solution?

**Comment by pgeh** [comment] 2024-03-06 15:47
@mholt I added a PR with a possible fix. 
BUT I now learned that this doesn't actually work with my split DNS setup when I'm actually in the internal network (instead of using VPN where it worked yesterday). It should probably fix it for @MisterDuval but not for me.

Also this PR does only use A records at the moment and doesn't work with IPv6 as I'm not sure how and if I should implement this properly.

My question now is: Would a working solution be to skip the check of the authoritative nameservers if there are resolvers given? I think it wouldn't contradict the documentation for the resolvers option and would fit the intention of the user in checking if the TXT is available via the given resolvers.

**Comment by mholt** [comment] 2024-03-06 19:30
@pgeh Thanks for the PR! I think I see what you mean now.

> My question now is: Would a working solution be to skip the check of the authoritative nameservers if there are resolvers given?

That... might make sense, yeah. The authoritative check is, of course, important to get a view like what the CA will when it does its authoritative lookup. If specifying your own resolvers is the only way to overcome the split horizon DNS situation, then maybe we should just do that. The user will have to configure resolvers that it is confident will return an authoritative lookup though.

**Comment by pgeh** [comment] 2024-03-08 07:38
@mholt Any suggestions on how to move forward with this? I would gladly provide a PR with my idea of skipping the authoritative nameserver check when resolvers are given, but I can't tell if you actually approved the idea. I know this is probably a very niche problem, but it would allow me to switch from certbot (which works with my DNS setup, but needs to be replaced due to other reasons) to caddy.

**Comment by mholt** [comment] 2024-03-08 10:23
Yeah let's see a PR if you have a moment! Sorry to be unclear. I think it's worth exploring it just sounds like it's up to the user to choose good resolvers that reflect what the CA would see accurately.

**Comment by pgeh** [comment] 2024-03-12 09:18
Ok, I can change my PR to require only one successful check. Can this also change for the default behavior so that one successful authoritative nameserver check is enough? It would be an easier fix, I just have to adjust the loop in checkNameservers(). But if I should preserve the original behavior that's ok too, just takes some more effort.

**Comment by francislavoie** [comment] 2024-03-12 09:28
IMO yes, one success is enough, but Matt may have a different opinion so I'll let him chime in first.

**Comment by mholt** [comment] 2024-03-14 15:23
I agree one authoritative check -- for our purposes -- is enough. Of course it's more brittle than multiple, multi-vantage lookups, but we're not a CA here :)

**Comment by pgeh** [comment] 2024-03-14 16:58
@mholt I updated the PR request to now require only one nameserver check to have the record in order to succeed. https://github.com/caddyserver/certmagic/pull/274

**Comment by mholt** [comment] 2024-03-14 21:21
Thank you @pgeh! We'll give it a shot :)

**Closed by mholt** 2024-03-14 21:21 UTC
Labels: bug, help wanted
