### ISSUE TITLE
Custom HTTP Challenge Handler?

### ISSUE THREAD

**Issue by coolaj86** [caddyserver/certmagic#104] opened 2020-10-10 06:42 UTC
I've got a special use case with a special problem (related to the go port of [telebit](https://telebit.cloud)).

I have a weird situation involving devices on private networks, tunneling, firewalls, and finicky DNS that the only solution that I can see is to **push HTTP challenge artifacts** to a trusted public-facing server and that presents them.

I've looked over the documentation and I can't seem to find a custom http challenge handler.

Does one exist? If not, would you be open to be adding one?

## Can't use DNS

Typically in this scenario, DNS challenges would be the correct choice, however, I have to support a DNS provider which has _wildly_ different propagation times between ns1, ns2, ns3, etc.

Even after pre-check validation completes, and after an additional custom wait of 45+ seconds, the Let's Encrypt Servers (which appear to be in globally diverse regions) can hit an NS server (also in globally diverse regions) to which the challenge has not yet propagated... and fail.

## Can't use ALPN

I can't use ALPN validation because the access to some of these devices is controlled by an IP/Port whitelist and the Let's Encrypt servers won't be on that whitelist.

> There isn’t and such a list won’t be made in the future too. Let’s Encrypt keeps the right to change the IP addresses used for authentication at will and won’t release lists of it for security reasons.

Ironically, port 80 is clear to use because the public-facing gateway doesn't forward any unencrypted traffic to the internal devices, so the gateway can capture all port 80 traffic indiscriminately.

**Comment by mholt** [comment] 2020-10-12 21:02
What do you mean by "custom http challenge handler?" Can you describe your situation in more detail? Right now my only understanding is that you have decided a solution but I don't even know what the problem is.

**Comment by coolaj86** [comment] 2020-10-12 21:23
I think you call it "Solver" and "Presenter" in your code. You've got one for DNS:

```go
import "github.com/libdns/cloudflare"

certmagic.DefaultACME.DNS01Solver = &certmagic.DNS01Solver{
	DNSProvider: cloudflare.Provider{
		APIToken: "topsecret",
	},
}
```

I want one for HTTP:

```go
import "github.com/xxx/http01"

certmagic.DefaultACME.HTTP01Solver = &certmagic.HTTP01Solver{
	HTTPProvider: http01.Provider{
		APIToken: "topsecret",
	},
}
```

**Comment by mholt** [comment] 2020-10-12 22:30
I see. Okay, will give it some thought!

**Comment by coolaj86** [comment] 2020-11-03 05:13
I was digging around, hoping that there would be some way for me to create an `acmez.Client` or provide the storage mechanism to the `distributedSolver`, and I came across this in `solvers.go`:

```go
err := dhs.acmeManager.config.Storage.Store(dhs.challengeTokensKey(chal.Identifier.Value), infoBytes)
```

It appears that the distributed solver is using the storage engine that's intended for the certificates?

**Comment by francislavoie** [comment] 2020-11-03 05:15
> It appears that the distributed solver is using the storage engine that's intended for the certificates?

Correct, that's to provide easy clustering in Caddy by sharing the same storage backend.

https://caddyserver.com/docs/automatic-https#storage

**Comment by mholt** [comment] 2021-03-12 04:09
Closing, since `GetACMEChallenge()` should be able to make equivalent functionality possible. I think. (https://github.com/caddyserver/certmagic/commit/7271e2f615920738553778ee531d22196191210c) Feel free to continue discussion or reopen if necessary!

**Closed by mholt** 2021-03-12 04:09 UTC
Labels: feature request
